### PR TITLE
[wip] Make readme suitable for broadcasting during people's arrivals

### PR DESCRIPTION
**Pull request by rkdarst**
- Let people know "yes, this is the right room"
- Link them the most important things that people should do when they
  first arrive.

I'm not sure what else needs to be added to this...

### CODE REVIEW

**Review by bast — APPROVED** [review]
Great.

**Comment by bast** [comment]
Please ping me once this is ready to go - looks ready to go from my perspective.

**Comment by bast** [comment]
I am merging since I might not have time to react tomorrow early. Looks good.

**Comment by rkdarst** [comment]
Thanks.... I agree it was ready to go, I couldn't think of much else.

**Pull request merged**
