### PR TITLE
video: Attempt to simplify some, remove redundant info and rearrange

### PR DESCRIPTION
**Pull request by rkdarst**
- As discovered is needed while presenting this
- Review: worth a read

### CODE REVIEW

**Comment by bast** [comment]
I am unsure which part of the conflict to keep here.

**Comment by rkdarst** [comment]
resolved

**Comment by rkdarst** [comment]
strategy here: know that one side just added `.` to sentences for consistency, took the other side.  Though I realize I forgot to add the `.` back in, but that does'nt matter.

**Comment by bast** [comment]
I should have checked in the terminal but on GitHub it did not look so obvious.

**Pull request merged**
