### PR TITLE
Code for creating participant map

### PR DESCRIPTION
**Pull request by samumantha**
* Jupyter notebook for creating participant map
* example praticipant csv file
* Europe files from Eurostat (boundaries and areas)

### CODE REVIEW

**Comment by bast** [comment]
I will update the data as I go through registrations tonight.

**Comment by bast** [comment]
But actually this is potentially a better place for the notebook: https://github.com/coderefinery/2022-03-22-workshop

**Comment by samumantha** [comment]
Ok, I mixed it up from chat. Will move it to workshop page.

**Comment by bast** [comment]
Latest counts (even if they change, that's good enough approximation):
```
      1 Bangladesh
     11 Denmark
     35 Finland
      1 France
      5 Germany
      1 India
      2 Italy
     48 Netherlands
     77 Norway
      1 Pakistan
     15 Spain
     41 Sweden
      2 United States
```

**Comment by samumantha** [comment]
Moved to workshop page

**Pull request closed without merging**
